version: '3'
services:
  web:
    container_name: github-requests-app
    build:
      context: .
      dockerfile: ./infrastructure/docker/${NODE_ENV}/Dockerfile
    ports:
      - "${PORT}:3000"
    volumes:
      - ./:/app
    environment:
      - AUTH_SIGN_IN_URL=${AUTH_SIGN_IN_URL}
      - BASE_URL=${BASE_URL}
      - CDN_HOST=${CDN_HOST}
      - COOKIE_ID_NAME=${COOKIE_ID_NAME}
      - COOKIE_PARSER_SECRET=${COOKIE_PARSER_SECRET}
      - COOKIE_SESSION_SECRET=${COOKIE_SESSION_SECRET}
      - FEATURE_FLAG_ENABLE_AUTH=${FEATURE_FLAG_ENABLE_AUTH}
      - GITHUB_KEY=${GITHUB_KEY}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO_ISSUE_ASSIGNEE=${GITHUB_REPO_ISSUE_ASSIGNEE}
      - GITHUB_REPO_ISSUE_LABEL=${GITHUB_REPO_ISSUE_LABEL}
      - GITHUB_TERRAFORM_REPO=${GITHUB_TERRAFORM_REPO}
      - DEPARTMENT_NAME=${DEPARTMENT_NAME}
      - GITHUB_ORG_NAME=${GITHUB_ORG_NAME}
      - HUMAN=${HUMAN}
      - LOG_LEVEL=${LOG_LEVEL}
      - MATOMO_URL=${MATOMO_URL}
      - NODE_ENV=${NODE_ENV}
      - NODE_SSL_ENABLED=${NODE_SSL_ENABLED}
      - PATH_SSL_CERTIFICATE=${PATH_SSL_CERTIFICATE}
      - PATH_SSL_PRIVATE_KEY=${PATH_SSL_PRIVATE_KEY}
      - SESSION_APP_KEY=${SESSION_APP_KEY}
      - SESSION_ID_NAME=${SESSION_ID_NAME}
      - USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
      - USER_POOL_ID=${USER_POOL_ID}
